name: Flutter Tests EJEMPLO
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.5.0
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test