name: Flutter Tests EJEMPLO
on: [push, pull_request]
jobs:
  flutter_test_dev:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
      - run: flutter --version
      - run: flutter pub get
      - name: FLUTTER TEST
        run: flutter test